language: csharp
dist: trusty
mono: none
solution: QuadTrees.sln
dotnet: 2.0.0
script:
- dotnet build QuadTrees.Core/QuadTrees.Core.csproj
- dotnet test QuadTrees.Core.Tests/QuadTrees.Core.Tests.csproj
- dotnet publish QuadTrees.Core/QuadTrees.Core.csproj
